# Generated by Django 3.0.14 on 2023-08-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('users_id', models.TextField(blank=True, unique=True)),
                ('users_password', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.TextField(blank=True, unique=True)),
                ('petage', models.TextField(blank=True)),
                ('petgender', models.TextField(blank=True)),
                ('petcomment', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users_id', models.ForeignKey(blank=True, db_column='users_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.User', to_field='users_id')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petresult', models.TextField(blank=True)),
                ('petresultper', models.TextField(blank=True)),
                ('diagday', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet_name', models.ForeignKey(blank=True, db_column='pet_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.Pet', to_field='petname')),
            ],
        ),
    ]
