# Generated by Django 3.0.14 on 2023-07-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, unique=True)),
                ('phone', models.TextField(blank=True)),
                ('email', models.TextField(blank=True)),
                ('user_id', models.TextField(blank=True)),
                ('user_password', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='upload',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='petname',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='username',
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.TextField(blank=True, unique=True)),
                ('petage', models.TextField(blank=True)),
                ('petgender', models.TextField(blank=True)),
                ('petcomment', models.TextField(blank=True)),
                ('status', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(blank=True, db_column='username', null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.User')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petresult', models.TextField(blank=True)),
                ('petresultper', models.TextField(blank=True)),
                ('diagday', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('petname', models.ForeignKey(blank=True, db_column='petname', null=True, on_delete=django.db.models.deletion.CASCADE, to='uploader.Pet')),
            ],
        ),
    ]
